spring: 
  zipkin:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver    
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: password
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
eureka:
  client:
    serviceUrl: 
      defaultZone: http://127.0.0.1:1001/eureka

feign:
  hystrix:
    enabled: false

citylife: 
  function: 
    mdcFilterEnabled: true

 

